-- ==============================================================================
-- BANK PORTFOLIO (CORE BANKING SYSTEM) - OPTIMIZED COMPACT SCRIPT
-- ==============================================================================

-- BÖLÜM 1: SCHEMA & PERMISSIONS
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER Bank_portfolio IDENTIFIED BY "Bank_07" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA 200M ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, CREATE SYNONYM TO Bank_portfolio;

-- BÖLÜM 2: BRANCHES
CREATE TABLE BRANCHES (
    branch_code NUMBER PRIMARY KEY,
    branch_name VARCHAR2(100) NOT NULL,
    city VARCHAR2(50) NOT NULL,
    opened_date DATE DEFAULT SYSDATE,
    status VARCHAR2(10) CHECK (status IN ('ACTIVE', 'CLOSED')),
    director VARCHAR2(100)
);

-- BÖLÜM 3: CUSTOMERS
CREATE TABLE CUSTOMERS (
    cif NUMBER PRIMARY KEY,
    full_name VARCHAR2(150) NOT NULL,
    customer_type CHAR(1) CHECK (customer_type IN ('I', 'C')),
    pin VARCHAR2(20),
    voen VARCHAR2(20) UNIQUE,
    phone VARCHAR2(20),
    email VARCHAR2(100) UNIQUE,
    birth_date DATE,
    created_at DATE DEFAULT SYSDATE,
    status VARCHAR2(10) CHECK (status IN ('ACTIVE', 'CLOSED', 'BLOCKED'))
);

-- BÖLÜM 4: ACCOUNTS
CREATE TABLE ACCOUNTS (
    account_no VARCHAR2(20) PRIMARY KEY,
    cif NUMBER,
    branch_code NUMBER,
    currency CHAR(3) CHECK (currency IN ('AZN','USD','EUR')),
    balance NUMBER DEFAULT 0 CHECK(balance >= 0),
    opened_date DATE DEFAULT SYSDATE,
    status VARCHAR2(10) CHECK(status IN ('ACTIVE','CLOSED','BLOCKED')),
    CONSTRAINT fk_accounts_customers FOREIGN KEY(cif) REFERENCES customers(cif),
    CONSTRAINT fk_accounts_branches FOREIGN KEY(branch_code) REFERENCES branches(branch_code)
);

-- BÖLÜM 5: TRANSACTIONS
CREATE TABLE TRANSACTIONS (
    txn_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_no VARCHAR2(20),
    txn_type VARCHAR2(10) CHECK (txn_type IN ('DEBIT','CREDIT')),
    amount NUMBER CHECK (amount > 0),
    currency CHAR(3) CHECK (currency IN ('AZN','USD','EUR')),
    txn_date DATE DEFAULT SYSDATE,
    description VARCHAR2(250),
    CONSTRAINT fk_txns_accounts FOREIGN KEY(account_no) REFERENCES accounts(account_no)
);

-- BÖLÜM 6: LOANS
CREATE TABLE LOANS (
    loan_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cif NUMBER,
    account_no VARCHAR2(20),
    loan_amount NUMBER CHECK (loan_amount > 0),
    interest_rate NUMBER CHECK (interest_rate > 0),
    principal_debt NUMBER DEFAULT 0,
    interest_debt NUMBER DEFAULT 0,
    penalty_debt NUMBER DEFAULT 0,
    start_date DATE DEFAULT SYSDATE,
    end_date DATE,
    status VARCHAR2(10) CHECK(status IN('ACTIVE','CLOSED','OVERDUE')),
    CONSTRAINT fk_loans_accounts FOREIGN KEY (account_no) REFERENCES accounts(account_no),
    CONSTRAINT fk_loan_dates CHECK(end_date > start_date)
);

-- BÖLÜM 7: CARDS
CREATE TABLE CARDS (
    card_no VARCHAR2(16) PRIMARY KEY,
    account_no VARCHAR2(20) NOT NULL,
    card_type VARCHAR2(10) CHECK(card_type IN ('DEBIT','CREDIT')),
    expire_date DATE NOT NULL,
    status VARCHAR2(10) CHECK(status IN('ACTIVE','BLOCKED','EXPIRED')),
    CONSTRAINT fk_cards_accounts FOREIGN KEY(account_no) REFERENCES accounts(account_no)
);

-- BÖLÜM 8: SEQUENCES
CREATE SEQUENCE seq_txn_id START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_loan_id START WITH 1 INCREMENT BY 1 NOCACHE;

-- BÖLÜM 9: TRIGGERS
CREATE OR REPLACE TRIGGER trg_transactions_bi BEFORE INSERT ON transactions FOR EACH ROW
BEGIN
    IF :NEW.txn_id IS NULL THEN SELECT seq_txn_id.nextval INTO :NEW.txn_id FROM dual; END IF;
END;
/
CREATE OR REPLACE TRIGGER trg_loans_auto_id BEFORE INSERT ON loans FOR EACH ROW
BEGIN
    IF :NEW.loan_id IS NULL THEN SELECT seq_loan_id.nextval INTO :NEW.loan_id FROM dual; END IF;
END;
/

-- BÖLÜM 10: INDEXES
CREATE INDEX idx_accounts_cif ON accounts(cif);
CREATE INDEX idx_accounts_branch_code ON accounts(branch_code);
CREATE INDEX idx_transactions_account_no ON transactions(account_no);
CREATE INDEX idx_transactions_txn_date ON transactions(txn_date);
CREATE INDEX idx_loans_cif ON loans(cif);
CREATE INDEX idx_loans_account_no ON loans(account_no);
CREATE INDEX idx_cards_account_no ON cards(account_no);

-- BÖLÜM 11: DATA POPULATION (DML)
INSERT INTO branches VALUES (1, 'Mərkəz Filialı', 'Bakı', to_date('2020-01-01','yyyy-mm-dd'), 'ACTIVE', 'Anar Əliyev');
INSERT INTO branches VALUES (2, 'Nərimanov Filialı', 'Bakı', to_date('2021-03-15','yyyy-mm-dd'), 'ACTIVE', 'Elvin Həsənov');
INSERT INTO branches VALUES (3, 'Gənclik Filialı', 'Bakı', to_date('2021-06-20','yyyy-mm-dd'), 'ACTIVE', 'Leyla Məmmədova');
INSERT INTO branches VALUES (4, 'Yasamal Filialı', 'Bakı', to_date('2022-02-10','yyyy-mm-dd'), 'ACTIVE', 'Rəşad Hüseynov');
INSERT INTO branches VALUES (5, 'Gəncə Filialı', 'Gəncə', to_date('2019-11-12','yyyy-mm-dd'), 'ACTIVE', 'Vüqar Məmmədov');
INSERT INTO branches VALUES (6, 'Sumqayıt Filialı', 'Sumqayıt', to_date('2022-08-01','yyyy-mm-dd'), 'ACTIVE', 'Elnur Qasımov');
INSERT INTO branches VALUES (7, 'Xətai Filialı', 'Bakı', to_date('2023-01-15','yyyy-mm-dd'), 'ACTIVE', 'Fərid Abdullayev');
INSERT INTO branches VALUES (8, 'Naxçıvan Filialı', 'Naxçıvan', to_date('2020-05-20','yyyy-mm-dd'), 'ACTIVE', 'Emin Novruzov');
INSERT INTO branches VALUES (9, 'Sabunçu Filialı', 'Bakı', to_date('2024-04-18','yyyy-mm-dd'), 'ACTIVE', 'Tural Bağırov');
INSERT INTO branches VALUES (10, 'Köhnə Filial', 'Bakı', to_date('2015-01-01','yyyy-mm-dd'), 'CLOSED', 'Rauf Əliyev');
INSERT INTO branches VALUES (11, 'Lənkəran Filialı', 'Lənkəran', to_date('2023-07-22','yyyy-mm-dd'), 'ACTIVE', 'Zaur Əhmədov');
INSERT INTO branches VALUES (12, 'Xırdalan Filialı', 'Xırdalan', to_date('2025-02-05','yyyy-mm-dd'), 'ACTIVE', 'Kamran Sultanov');

DECLARE
    v_type CHAR(1); v_status VARCHAR2(10);
BEGIN
    FOR i IN 1..45 LOOP
        IF MOD(i, 2) = 0 THEN v_type := 'I'; ELSE v_type := 'C'; END IF;
        IF i = 13 THEN v_status := 'BLOCKED'; ELSIF i = 25 THEN v_status := 'CLOSED'; ELSE v_status := 'ACTIVE'; END IF;
        INSERT INTO customers VALUES (1000 + i, CASE WHEN v_type = 'I' THEN 'Müştəri_'||i||' Əliyev' ELSE 'Şirkət_'||i||' MMC' END, v_type, CASE WHEN v_type = 'I' THEN 'PIN'||(85473+i) ELSE NULL END, CASE WHEN v_type = 'C' THEN 'VOEN'||(9900123+i) ELSE NULL END, '+99450'||(1234560+i), CASE WHEN i IN (5, 15, 35) THEN NULL ELSE 'customer_'||i||'@mail.com' END, to_date('1990-01-01','yyyy-mm-dd')+i*100, SYSDATE-(60-i), v_status);
    END LOOP;
END;
/

DECLARE
    v_curr CHAR(3); v_bal NUMBER; v_br NUMBER; v_cf NUMBER;
BEGIN
    FOR i IN 1..75 LOOP
        IF MOD(i, 3) = 0 THEN v_curr := 'AZN'; ELSIF MOD(i, 3) = 1 THEN v_curr := 'USD'; ELSE v_curr := 'EUR'; END IF;
        v_cf := 1000 + MOD(i, 45) + 1; v_br := MOD(i, 12) + 1;
        IF i IN (10, 25, 40, 55) THEN v_bal := 0; ELSIF i IN (5, 15, 35, 65) THEN v_bal := 450; ELSE v_bal := 250 * i; END IF;
        INSERT INTO accounts VALUES ('AZE'||(100000+i), v_cf, v_br, v_curr, v_bal, SYSDATE-MOD(i, 45), 'ACTIVE');
    END LOOP;
END;
/

DECLARE
    v_acc VARCHAR2(20); v_tp VARCHAR2(10); v_cr CHAR(3); v_ls VARCHAR2(10); v_cs VARCHAR2(10);
BEGIN
    FOR i IN 1..130 LOOP
        v_acc := 'AZE'||(100000+MOD(i, 75)+1);
        IF MOD(i, 2) = 0 THEN v_tp := 'DEBIT'; ELSE v_tp := 'CREDIT'; END IF;
        IF MOD(i, 3) = 0 THEN v_cr := 'AZN'; ELSIF MOD(i, 3) = 1 THEN v_cr := 'USD'; ELSE v_cr := 'EUR'; END IF;
        INSERT INTO transactions (account_no, txn_type, amount, currency, txn_date, description) VALUES (v_acc, v_tp, 40+(i*3), v_cr, SYSDATE-MOD(i, 12), 'Onlayn ödəniş №'||i);
    END LOOP;
    FOR i IN 1..18 LOOP
        IF i IN (4, 9, 14) THEN v_ls := 'OVERDUE'; ELSIF i IN (7, 18) THEN v_ls := 'CLOSED'; ELSE v_ls := 'ACTIVE'; END IF;
        INSERT INTO loans (cif, account_no, loan_amount, interest_rate, principal_debt, interest_debt, penalty_debt, start_date, end_date, status) VALUES (1000+MOD(i, 45)+1, 'AZE'||(100000+i), 4000+(i*1200), 10+MOD(i, 6), 2500, 350, CASE WHEN v_ls='OVERDUE' THEN 200 ELSE 0 END, SYSDATE-120, SYSDATE+240, v_ls);
    END LOOP;
    FOR i IN 1..25 LOOP
        IF i IN (3, 12, 21) THEN v_cs := 'BLOCKED'; ELSE v_cs := 'ACTIVE'; END IF;
        INSERT INTO cards VALUES ('41697300554433'||(10+i), 'AZE'||(100000+i), CASE WHEN MOD(i, 2)=0 THEN 'DEBIT' ELSE 'CREDIT' END, SYSDATE+1095, v_cs);
    END LOOP;
END;
/
COMMIT;

-- AUDIT COUNT REPORT
SELECT 'Branches' AS cedvel, COUNT(*) AS say FROM branches UNION ALL
SELECT 'Customers', COUNT(*) FROM customers UNION ALL
SELECT 'Accounts', COUNT(*) FROM accounts UNION ALL
SELECT 'Transactions', COUNT(*) FROM transactions UNION ALL
SELECT 'Loans', COUNT(*) FROM loans UNION ALL
SELECT 'Cards', COUNT(*) FROM cards;

-- BÖLÜM 12: WHERE CLAUSES
SELECT * FROM customers WHERE status = 'ACTIVE';
SELECT * FROM customers WHERE status = 'CLOSED';
SELECT * FROM accounts WHERE balance > 1000;
SELECT * FROM customers WHERE cif IN (SELECT cif FROM accounts WHERE currency = 'USD');
SELECT * FROM transactions WHERE txn_date >= SYSDATE - 7;
SELECT * FROM loans WHERE status = 'OVERDUE';
SELECT * FROM cards WHERE status = 'BLOCKED';
SELECT * FROM customers WHERE email IS NULL;
SELECT * FROM accounts WHERE balance = 0;
SELECT * FROM accounts WHERE opened_date >= TRUNC(SYSDATE,'MM');

-- BÖLÜM 13: JOINS & GROUP BY
SELECT c.full_name, a.account_no, a.currency, a.balance FROM customers c JOIN accounts a ON c.cif = a.cif;
SELECT a.account_no, b.branch_name, b.city FROM accounts a JOIN branches b ON a.branch_code = b.branch_code;
SELECT c.full_name, l.loan_id, l.loan_amount, l.status FROM customers c JOIN loans l ON c.cif = l.cif;
SELECT a.account_no, t.txn_id, t.txn_type, t.amount, t.txn_date FROM accounts a JOIN transactions t ON a.account_no = t.account_no;
SELECT c.card_no, c.status, cu.full_name FROM cards c JOIN accounts a ON c.account_no = a.account_no JOIN customers cu ON a.cif = cu.cif;
SELECT b.branch_name, COUNT(DISTINCT a.cif) AS musteri_sayi FROM branches b JOIN accounts a ON b.branch_code = a.branch_code GROUP BY b.branch_name;
SELECT b.branch_name, COUNT(a.account_no) AS hesab_sayi FROM branches b JOIN accounts a ON b.branch_code = a.branch_code GROUP BY b.branch_name;
SELECT c.full_name, SUM(a.balance) AS umumi_balans FROM customers c JOIN accounts a ON c.cif = a.cif GROUP BY c.full_name;
SELECT c.full_name, c.cif, l.loan_amount, l.status FROM customers c JOIN loans l ON c.cif = l.cif;
SELECT DISTINCT cu.full_name, cu.cif FROM customers cu JOIN accounts a ON cu.cif = a.cif JOIN cards ca ON a.account_no = ca.account_no WHERE cu.cif NOT IN (SELECT cif FROM loans WHERE cif IS NOT NULL);

-- BÖLÜM 14: AGGREGATIONS
SELECT currency, SUM(balance) AS toplam_balans FROM accounts GROUP BY currency;
SELECT branch_code, SUM(balance) AS filial_toplam_balans FROM accounts GROUP BY branch_code;
SELECT customer_type, COUNT(*) AS musteri_sayi FROM customers GROUP BY customer_type;
SELECT account_no, COUNT(*) AS transaksiya_sayi FROM transactions GROUP BY account_no;
SELECT account_no, txn_type, SUM(amount) AS toplam_mebleg FROM transactions GROUP BY account_no, txn_type;
SELECT account_no, COUNT(*) AS transaksiya_sayi FROM transactions GROUP BY account_no HAVING COUNT(*) > 3;
SELECT cif, SUM(balance) AS toplam_balans FROM accounts GROUP BY cif HAVING SUM(balance) > 5000;
SELECT status, COUNT(*) AS hesab_sayi FROM accounts GROUP BY status;
SELECT status, SUM(loan_amount) AS toplam_kredit_meblegi FROM loans GROUP BY status;
SELECT TO_CHAR(txn_date, 'yyyy-mm') AS ay, COUNT(*) AS transaksiya_sayi, SUM(amount) AS toplam_mebleg FROM transactions GROUP BY TO_CHAR(txn_date, 'yyyy-mm');

-- BÖLÜM 15: WINDOW FUNCTIONS
SELECT * FROM (SELECT account_no, txn_id, txn_type, amount, txn_date, ROW_NUMBER() OVER (PARTITION BY account_no ORDER BY txn_date DESC) as rn FROM transactions) WHERE rn = 1;
SELECT * FROM (SELECT account_no, branch_code, balance, currency, ROW_NUMBER() OVER (PARTITION BY branch_code ORDER BY balance DESC) as rank FROM accounts) WHERE rank <= 3;
SELECT account_no, currency, balance, DENSE_RANK() OVER (PARTITION BY currency ORDER BY balance DESC) AS valyuta_ranki FROM accounts;
SELECT cif, account_no, currency, balance, ROW_NUMBER() OVER (PARTITION BY cif ORDER BY balance DESC) AS musteri_ici_sira FROM accounts;
SELECT account_no, txn_id, txn_date, amount, txn_type, SUM(CASE WHEN txn_type = 'CREDIT' THEN amount ELSE -amount END) OVER (PARTITION BY account_no ORDER BY txn_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) as running_balance FROM transactions;
WITH m_data AS (SELECT TO_CHAR(txn_date, 'yyyy-mm') as ay, SUM(amount) as c_toplam FROM transactions GROUP BY TO_CHAR(txn_date, 'yyyy-mm')) SELECT ay, c_toplam, LAG(c_toplam, 1) OVER (ORDER BY ay) as e_toplam, (c_toplam - LAG(c_toplam, 1) OVER (ORDER BY ay)) as ferq FROM m_data;
SELECT * FROM (SELECT cif, account_no, currency, balance, ROW_NUMBER() OVER (PARTITION BY cif ORDER BY balance DESC) as rn FROM accounts) WHERE rn = 1;
SELECT loan_id, cif, loan_amount, interest_rate, DENSE_RANK() OVER (ORDER BY interest_rate DESC) as faiz_ranki FROM loans;
SELECT b.branch_name, a.cif, SUM(a.balance) as toplam_balans, DENSE_RANK() OVER (PARTITION BY a.branch_code ORDER BY SUM(a.balance) DESC) as filial_ici_musteri_ranki FROM accounts a JOIN branches b ON a.branch_code = b.branch_code GROUP BY b.branch_name, a.branch_code, a.cif;
SELECT account_no, txn_date as son_txn_tarixi, TRUNC(SYSDATE - txn_date) as kecen_gun_sayi FROM (SELECT account_no, txn_date, ROW_NUMBER() OVER (PARTITION BY account_no ORDER BY txn_date DESC) as rn FROM transactions) WHERE rn = 1;

-- BÖLÜM 16: SUBQUERIES & EXISTS
SELECT * FROM customers c WHERE NOT EXISTS (SELECT 1 FROM accounts a WHERE a.cif = c.cif);
SELECT * FROM accounts a WHERE NOT EXISTS (SELECT 1 FROM transactions t WHERE t.account_no = a.account_no);
SELECT * FROM customers c WHERE EXISTS (SELECT 1 FROM loans l WHERE l.cif = c.cif);
SELECT * FROM accounts a WHERE NOT EXISTS (SELECT 1 FROM cards card WHERE card.account_no = a.account_no);
SELECT * FROM accounts WHERE balance > (SELECT AVG(balance) FROM accounts);
SELECT * FROM customers WHERE cif = (SELECT cif FROM (SELECT cif FROM loans ORDER BY loan_amount DESC) WHERE ROWNUM = 1);
SELECT * FROM accounts a1 WHERE balance = (SELECT MAX(balance) FROM accounts a2 WHERE a2.branch_code = a1.branch_code);
SELECT * FROM accounts a WHERE status = 'ACTIVE' AND cif IN (SELECT cif FROM loans WHERE status = 'OVERDUE');
SELECT * FROM customers c WHERE EXISTS (SELECT 1 FROM accounts a JOIN cards card ON a.account_no = card.account_no WHERE a.cif = c.cif AND a.status = 'ACTIVE' AND card.status = 'BLOCKED');
SELECT * FROM customers c WHERE EXISTS (SELECT 1 FROM accounts a JOIN cards card ON a.account_no = card.account_no WHERE a.cif = c.cif) AND NOT EXISTS (SELECT 1 FROM loans l WHERE l.cif = c.cif);

-- BÖLÜM 17: DATABASE VIEWS
CREATE OR REPLACE VIEW v_customer_accounts AS SELECT c.full_name, c.cif, a.account_no, a.currency, a.balance, b.branch_name FROM customers c JOIN accounts a ON c.cif = a.cif JOIN branches b ON a.branch_code = b.branch_code;
CREATE OR REPLACE VIEW v_customer_total_balance AS SELECT c.cif, c.full_name, SUM(a.balance) as umumi_balans FROM customers c JOIN accounts a ON c.cif = a.cif GROUP BY c.cif, c.full_name;
CREATE OR REPLACE VIEW v_overdue_loans AS SELECT loan_id, cif, account_no, loan_amount, principal_debt, interest_debt, penalty_debt, status FROM loans WHERE status = 'OVERDUE';
CREATE OR REPLACE VIEW v_monthly_transactions AS SELECT TO_CHAR(txn_date, 'yyyy-mm') as ay, COUNT(*) as transaksiya_sayi, SUM(amount) as toplam_mebleg FROM transactions GROUP BY TO_CHAR(txn_date, 'yyyy-mm');
